[package]
name = "luatos-serial"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Serial port enumeration and log streaming"

[dependencies]
anyhow.workspace = true
serde.workspace = true
serialport.workspace = true
log.workspace = true
chrono.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = [
    "Win32_Foundation",
    "Win32_Devices_Communication",
] }
